# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@1.3.0

      - name: lint
        run: vendor/bin/phpstan analyse -n --no-progress -c phpstan.neon src/

  phpmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@1.3.0

      - name: PHPMD
        run: vendor/bin/phpmd src/ ansi phpmd.xml --exclude vendor/
